Add solves for Week 4. Character '_' removed from names of packages.
Hungryas/MTS_Java_Homework pull request #1
Opened 2022-03-10 18:53 UTC by Hungryas

Для проверки заданий Week 3, Week 4,

2022-03-21 13:27 UTC, kniffenfork requested changes

2022-03-21 13:27 UTC, kniffenfork commented on src/Week03/entities/Admin.java
>   * User of Admin group of Library.
ban/unban нужно в AdminService'е реализовывать)

2022-03-21 13:27 UTC, kniffenfork commented on src/Week03/entities/Client.java
>          super(firstName, lastName, middleName, phone);
Тут, в принципе, аналогично Admin'у -- Client это сугубо сущность для хранения данных тут

2022-03-21 13:27 UTC, kniffenfork commented on src/Week04/repository/impl/UserRepositoryImpl.java
> +        if (getListID().contains(id)) return users.get(listID.indexOf(id));
тут можно у юзеров переопределить хеш-код и еквалс и по полной воспользоваться contains уже с объектами User

2022-03-21 13:27 UTC, kniffenfork commented on src/Week04/repository/impl/UserRepositoryImpl.java
> +    public List<String> getListID() {
и тогда этот метод можно и не использовать будет

2022-03-21 13:27 UTC, kniffenfork commented on src/Week04/services/impl/UserServiceImpl.java
> +        if (user.getStatus() == UserStatus.ACTIVE) {
тут лучше как раз на !=ACTIVE проверять

2022-03-24 16:33 UTC, Hungryas commented on src/Week03/entities/Admin.java
>   * User of Admin group of Library.
перенес в AdminService

2022-03-24 16:34 UTC, Hungryas commented on src/Week03/entities/Client.java
>          super(firstName, lastName, middleName, phone);
Перенес в ClientService.

2022-03-24 16:34 UTC, mmefremov commented on src/Week04/repository/impl/UserRepositoryImpl.java
> +        if (getListID().contains(id)) return users.get(listID.indexOf(id));
Сделал.

2022-03-24 16:34 UTC, Hungryas commented on src/Week04/repository/impl/UserRepositoryImpl.java
> +    public List<String> getListID() {
Метод удалил.

2022-03-24 16:35 UTC, Hungryas commented on src/Week04/services/impl/UserServiceImpl.java
> +        if (user.getStatus() == UserStatus.ACTIVE) {
Переделал

2022-04-16 21:35 UTC, kniffenfork requested changes

2022-04-16 21:35 UTC, kniffenfork commented on src/Week05/service/exceptions/RoomNotFoundException.java
> +public class RoomNotFoundException extends Exception {
Обычно в бизнес логичных эксепшнах наследование идет от RuntimeException, а выбрасываемые исключения прописываются в @throws в javadoc'e

2022-04-16 21:35 UTC, kniffenfork commented on src/Week05/service/impl/BookingServiceImpl.java
> +        for (Booking booking : bookingRepository.getAll()) {
можно переписать как 
`bookingRepository.getAll().stream().filter(booking -> booking.getId().equals(id)).findAny().orElseThrow(() -> new BookingNotFoundException(id));`

2022-04-16 21:35 UTC, kniffenfork commented on src/Week05/service/impl/BookingServiceImpl.java
> +        if (booking.getCheckIn() == null) throw new RequiredFieldMissedException("Field \"CheckIn Date\" is missed");
это лучше вынести в отдельный метод `void validate`

2022-04-16 21:35 UTC, kniffenfork commented on src/Week05/service/impl/BookingServiceImpl.java
> +        if (bookingRepository.getBy(id) == null) throw new BookingNotFoundException();
аналогично

2022-04-16 21:35 UTC, kniffenfork commented on src/Week05/service/impl/RoomServiceImpl.java
> +            if (room.getId().equals(id)) return room;
тут тоже можно на стримах переписать)

2022-04-16 21:35 UTC, kniffenfork commented on src/Week05/service/impl/RoomServiceImpl.java
> +        if (room.getRoomNumber() == null) throw new RequiredFieldMissedException("Field \"Number\" is missed");
в отдельный метод также

2022-04-17 15:38 UTC, Hungryas commented on src/Week05/service/exceptions/RoomNotFoundException.java
> +public class RoomNotFoundException extends Exception {
унаследовался от RuntimeException в RoomNotFoundException и BookingNotFindException

2022-04-17 15:44 UTC, Hungryas commented on src/Week05/service/impl/BookingServiceImpl.java
> +        for (Booking booking : bookingRepository.getAll()) {
Выглядит отлично, переписал.

2022-04-17 16:55 UTC, Hungryas commented on src/Week05/service/impl/BookingServiceImpl.java
> +        if (booking.getCheckIn() == null) throw new RequiredFieldMissedException("Field \"CheckIn Date\" is missed");
вынес в validateBooking

2022-04-17 16:56 UTC, Hungryas commented on src/Week05/service/impl/BookingServiceImpl.java
> +        if (bookingRepository.getBy(id) == null) throw new BookingNotFoundException();
Вынес в validateBooking

2022-04-17 16:59 UTC, Hungryas commented on src/Week05/service/impl/RoomServiceImpl.java
> +            if (room.getId().equals(id)) return room;
переписал через стрим

2022-04-17 17:11 UTC, Hungryas commented on src/Week05/service/impl/RoomServiceImpl.java
> +        if (room.getRoomNumber() == null) throw new RequiredFieldMissedException("Field \"Number\" is missed");
Вынес validateRoom

2022-04-17 17:36 UTC, merged